modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="portalmod"
version="1.2.0"
displayName="PortalMod"
credits="Power by Swagouin"
displayURL="https://www.swagouin.ml"
authors="Swagouin : OxiWan"
description='''
Ceci et une description
'''

[[dependencies.portalmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




