modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="portalmod"
version="1.3.5"
displayName="PortalMod"
credits="Powers by Swagouin"
displayURL="https://www.swagouin.ml/mods/portalmod"
authors="Swagouin : OxiWan"
description='''
Decouvrez plien de dimension extraordinaire dans PortalMod V3
'''

[[dependencies.portalmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




